In [3]:
import numpy as np
import os
import matplotlib.pyplot as plt


root_dir = '/disk1/labeled/'
npyList = os.listdir(root_dir)
npyList = [root_dir+n for n in npyList]
result = []
label = []
for n,array in enumerate(npyList):
    result.append(np.load(array))
    label.append([n]*result[n].shape[0])
    
result = np.concatenate(result)
label = np.concatenate(label)

In [11]:
print(__doc__)

from time import time
import numpy as np
import matplotlib.pyplot as plt

from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn.datasets import load_digits
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale

np.random.seed(42)


data = result.reshape(result.shape[0],-1)

n_samples, n_features = data.shape
labels = label
n_digits = len(np.unique(label))

sample_size = 300

print("n_digits: %d, \t n_samples %d, \t n_features %d"
      % (n_digits, n_samples, n_features))


print(79 * '_')
print('% 9s' % 'init'
      '    time  inertia    homo   compl  v-meas     ARI AMI  silhouette')


def bench_k_means(estimator, name, data):
    t0 = time()
    estimator.fit(data)
    print('% 9s   %.2fs    %i   %.3f   %.3f   %.3f   %.3f   %.3f    %.3f'
          % (name, (time() - t0), estimator.inertia_,
             metrics.homogeneity_score(labels, estimator.labels_),
             metrics.completeness_score(labels, estimator.labels_),
             metrics.v_measure_score(labels, estimator.labels_),
             metrics.adjusted_rand_score(labels, estimator.labels_),
             metrics.adjusted_mutual_info_score(labels,  estimator.labels_),
             metrics.silhouette_score(data, estimator.labels_,
                                      metric='euclidean',
                                      sample_size=sample_size)))

bench_k_means(KMeans(init='k-means++', n_clusters=n_digits, n_init=10),
              name="k-means++", data=data)

bench_k_means(KMeans(init='random', n_clusters=n_digits, n_init=10),
              name="random", data=data)

# in this case the seeding of the centers is deterministic, hence we run the
# kmeans algorithm only once with n_init=1
pca = PCA(n_components=n_digits).fit(data)
bench_k_means(KMeans(init=pca.components_, n_clusters=n_digits, n_init=1),
              name="PCA-based",
              data=data)
print(79 * '_')

Automatically created module for IPython interactive environment
n_digits: 4, 	 n_samples 1971, 	 n_features 3072
_______________________________________________________________________________
init    time  inertia    homo   compl  v-meas     ARI AMI  silhouette
k-means++   8.32s    10954399027   0.190   0.162   0.175   0.141   0.161    0.119
   random   6.80s    10954565373   0.188   0.160   0.173   0.140   0.159    0.124
PCA-based   1.32s    10956567550   0.186   0.157   0.170   0.141   0.156    0.136
_______________________________________________________________________________


In [ ]:
r=result.reshape(result.shape[0],-1)
print len(r)

In [17]:
print(__doc__)

from time import time
import numpy as np
import matplotlib.pyplot as plt

from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn.datasets import load_digits
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale

np.random.seed(42)


data = result.reshape(result.shape[0],-1)

n_samples, n_features = data.shape
labels = label
n_digits = len(np.unique(label))

sample_size = 600

pca = PCA(n_components=5).fit(data)
kmean_methond= KMeans(init=pca.components_, n_clusters=5, n_init=10)
kmean_methond.fit(data)
prelabel = kmean_methond.labels_
print prelabel

Automatically created module for IPython interactive environment
[2 1 1 ..., 1 0 1]


In [18]:
l0,l1,l2,l3,l4 =0,0,0,0,0
a,b,c,d=742,477,34,718
for i in prelabel[0:a]:
    if i==0:
        l0=l0+1
    if i==1:
        l1=l1+1
    if i==2:
        l2=l2+1
    if i==3:
        l3=l3+1  
    if i==4:
        l4=l4+1  
L0=[l0,l1,l2,l3,l4]
l0,l1,l2,l3,l4 =0,0,0,0,0
for i in prelabel[a:a+b]:
    if i==0:
        l0=l0+1
    if i==1:
        l1=l1+1
    if i==2:
        l2=l2+1
    if i==3:
        l3=l3+1  
    if i==4:
        l4=l4+1  
L1=[l0,l1,l2,l3,l4]
l0,l1,l2,l3,l4 =0,0,0,0,0
for i in prelabel[a+b:a+b+c]:
    if i==0:
        l0=l0+1
    if i==1:
        l1=l1+1
    if i==2:
        l2=l2+1
    if i==3:
        l3=l3+1  
    if i==4:
        l4=l4+1  
L2=[l0,l1,l2,l3,l4]
l0,l1,l2,l3,l4 =0,0,0,0,0
for i in prelabel[a+b+c:a+b+c+d]:
    if i==0:
        l0=l0+1
    if i==1:
        l1=l1+1
    if i==2:
        l2=l2+1
    if i==3:
        l3=l3+1  
    if i==4:
        l4=l4+1  
L3=[l0,l1,l2,l3,l4]
c = np.array([L0,L1,L2,L3])
print c
print ((330.0)/c[0].sum(),332.0/c[1].sum(),18.0/c[2].sum(),(219.0+204.0)/c[3].sum())
print (330.0+332.0+18.0+219.0+204.0)/(len(labels))

[[ 44 215 330 101  52]
 [ 39  59  30  17 332]
 [  2  18   1   9   4]
 [219 201  14 204  80]]
(0.444743935309973, 0.6960167714884696, 0.5294117647058824, 0.5891364902506964)
0.559614408929


In [ ]:
labels = label
pca = PCA(n_components=5).fit(result.reshape(result.shape[0],-1))
bench_k_means(KMeans(init=pca.components_, n_clusters=5, n_init=1),
              name="PCA-based",
              data=result.reshape(result.shape[0],-1))

In [ ]:
c = np.array([[1, 2, 3, 4],[4, 5, 6, 7], [7, 8, 9, 10]])
d=c.reshape(3,-1)
print d

In [ ]:
data = result.reshape(result.shape[0],-1)
n_samples, n_features = data.shape
print n_samples, n_features

In [ ]:
a.labels_